name: default weapons publish to store.nanos.world

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish package
    steps:
      - uses: actions/checkout@v2
      - name: Nanos Store Action
        uses: nanos-world/nanos-store-action@v2.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          # Folder which contains the asset/package - if it's on root, leave it blank
          folder: ''
          # Name of the asset/package.
          name: 'default-weapons'
          # API token - generate at https://store.nanos.world/settings/tokens/ and set under Settings -> Secrets -> Actions with name STORE_SECRET
          token: ${{ secrets.STORE_SECRET }}
